config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/sysadmin', as: 'rails_admin'
  devise_for :users
  root to: 'securities#index'

  namespace :admin do
    resources :statements, only: [:index]
    resources :securities do
      resources :bids
    end
    get 'mybids', to: 'bids#mybids'
  end

  resources :securities, only: [:index, :show] do
    member do
      post :calculate
    end

    collection do
      get 'search'
      get 'ajax_calculate'
    end
  end

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :buyer, class_name: 'User', foreign_key: :buyer_id
  belongs_to :seller, class_name: 'User', foreign_key: :seller_id
  belongs_to :security

  #validates :price, presence: true
  #validates :rate, presence: true

  def comission
    self.price*0.0025
  end
end

app/controllers/admin/bids_controller.rb
class Admin::BidsController < ApplicationController
  def index
    @security = Security.find(params[:security_id])
    @bids = @security.bids.order(price: :desc)
    @bid = @security.bids.where(status: true)
  end

  def create
    @security = Security.find(params[:security_id])
    @bid = Bid.new(bid_params)
    @bid.security = @security
    @bid.buyer = current_user
    @bid.seller = @security.user
    if @bid.save
      redirect_to admin_security_bids_path(@security)
    else
      render :show
    end
  end

  def update
    @security = Security.find(params[:security_id])
    @bid = Bid.find(params[:id])
    if current_user == @security.user
      @bid.status = true
      @security.status = @bid
      @bid.save!
      @security.save!
      redirect_to admin_security_bids_path
    else
      redirect_to admin_security_bids_path
    end
  end

  def destroy
      @security  = Security.find(params[:security_id])
      @bid = @security.bids.find(params[:id])
    if current_user == @security.user
      @bid.destroy
      redirect_to admin_security_bids_path
    end
  end

  def mybids
    @securities = Bid.where(buyer: current_user).map(&:security).uniq
  end

  private

  def bid_params
    params.require(:bid).permit(:price, :rate, :indexer)
  end

end

app/views/admin/bids/index.html.erb
<style >
.congratulations p{
  font-size: 25px;
  font-weight: 300;
}

</style>

<br>
<%= link_to "Voltar para busca", search_securities_path, class: "links" %>
<div class="row">
  <div class="col-md-9">
    <% if @bids.empty? %>
      <% if current_user == @security.user %>
        <h1 style="font-size:32px;">Você ainda não possui ofertas para este título.</h1>
      <% else %>
        <h1 style="font-size:32px;">Seja o primeiro a dar um lance!</h1>
        <%= link_to "Ir para a página do título", security_path(@security), class: "btn btn-navy-blue" %>
        <br>
        <br>
      <% end %>
    <% else %>
      <% if !@security.status.nil? %>
        <div class="bid-title">
          <h3 style="font-size:32px;">Título Vendido!</h3>
            <div class="offer" id="best">
              <i class="fa fa-star" aria-hidden="true"></i>
              <div class="congratulations">
                <p>Parabéns! Você vendeu seu título</p>
                <p>Lance Vencedor: <strong><%= number_to_currency(@bid.first.price) %></strong> </p>
              </div>
            </div>
        </div>
      <% else %>
        <h1 style="font-size:32px;">Lances recebidos:</h1>
        <h1 class="bid-title"> </h1>
        <% bids = @bids.to_a %>
        <% best_offer = bids.shift %>

        <div class="offer" id="best">
          <i class="fa fa-star" aria-hidden="true"></i>
            <div class="offer-info">

              <% rate = number_to_percentage(((best_offer.price-@security.current_value)/@security.current_value)*100, precision: 2) %>
              <h3><%= number_to_currency(best_offer.price)%> </h3>

              <p>Lance registrado em <%= best_offer.created_at.strftime("%d/%m/%Y") %></p>
              <p >Taxa sobre valor atual: <span style="color:<%= rate.to_f < 0 ? "red" : "green" %>;"><%= rate %> </span></p>
              <% if best_offer.buyer != current_user && @security.user != current_user%>
                <p><strong> Seu lance não é o maior, faça um lance maior para ganher este arremate! </strong></p>
              <% end %>
              </div>
              <% if current_user == @security.user %>
                <div id="controls">
                  <%= simple_form_for(["admin", @security, best_offer]) do |form| %>
                  <%= form.button :submit, "Aceitar", class: "btn btn-primary" %>
                  <% end %>
                  <%= link_to "Rejeitar", admin_security_bid_path(@security, best_offer.id), method: :delete, action: :destroy, class: "btn btn-danger" %>
               </div>
          <% end %>
        </div>

        <% bids.to_a.each do |bid| %>
          <div class="offer">
            <div class="offer-info">
              <p><%= number_to_currency(bid.price)%> - Lance registrado em <%= bid.created_at.strftime("%d/%m/%Y") %> - Taxa sobre valor atual: <%= number_to_percentage(((bid.price-@security.current_value)/@security.value)*100, precision: 2) %> </p>
              <% if bid.buyer == current_user %>
                  <h5>Faça um lance maior para ganhar este leilão</h5>
              <% end %>

            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <%= link_to "Voltar para meus títulos", admin_securities_path, class: "links" %>
  </div>
  <div class="col-md-3">
    <%=render 'shared/security_card', security: @security, link_path: security_path(@security) %>
  </div>
</div>

app/views/admin/bids/mybids.html.erb
<style>
.title-minha-ofertas h2 {
  margin: 10px;
}

</style>

<div class="container">
  <div class="title-minha-ofertas">
    <h2>Minhas ofertas enviadas</h2>
      <% if @securities.empty? %>
        <h3> Você não fez nenhuma oferta ainda </h1>
        <%= link_to "Veja os títulos disponíveis", search_securities_path %>
      <% else %>
        <% @securities.each do |security| %>
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
            <%=render 'shared/security_card', security: security, link_path: admin_security_bids_path(security) %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>
<!--
  <%# if @securities.empty? %>
    <h3> Você não fez nenhuma oferta ainda </h1>
    <%#= link_to "Veja os títulos disponíveis", search_securities_path %>
  <%# else %>
    <%# @securities.each do |security| %>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <%#=render 'shared/security_card', security: security, link_path:  admin_security_bids_path(security) %>
      </div>
    <%# end %>

  <%# end %>

 -->