config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/sysadmin', as: 'rails_admin'
  devise_for :users
  root to: 'securities#index'

  namespace :admin do
    resources :statements, only: [:index]
    resources :securities do
      resources :bids
    end
    get 'mybids', to: 'bids#mybids'
  end

  resources :securities, only: [:index, :show] do
    member do
      post :calculate
    end

    collection do
      get 'search'
      get 'ajax_calculate'
    end
  end

end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-135deg, rgba(0,63,191,0.5) 15%, rgba(50,78,123,0.95) 80%), url(<%= cl_image_path('banner_x5lv0l.jpg') %>);">
  <div class="col-xs-12 col-sm-offset-1 col-sm-11" >
    <h1>secondary.</h1>
    <p>A sua plataforma para negociar títulos de renda fixa.</p>
    <%= link_to "Venda seu título", new_admin_security_path, class: "btn btn-md btn-home" %>
    <%= link_to "Veja os títulos disponíveis", search_securities_path, class: "btn btn-md btn-home" %>
  </div>
</div>

app/views/shared/_bid_card.html.erb
<div class="bid-card text-center">
  <h3 class="text-logo">secondary.</h3>
  <%= simple_form_for :bid_calculation, url: calculate_security_path(@security), method: :post, remote: true do |f| %>
    <div class="form-inputs">
      <%= f.input :mode, as: :radio_buttons, label: "Faça sua oferta", collection: [:price, :rate], checked: :price %>
      <div class="price-mode">
        <%= f.input :masked_price, label: 'Valor de oferta (R$)', autofocus: true, input_html: { min: @security.price.to_f/10, value: @security.price.to_f/10, autofocus: true, id: "masked-money", data: {thousands: ".", decimal: ",", prefix:"R$ "} }, as: :string %>
        <%= f.input :price, as: :hidden, input_html: {id: "real-money"} %>
      </div>
      <div class="row">
        <div class="col-sm-6 rate-mode hidden">
        <%= f.input :masked_rate, label: 'Taxa oferta (%)', input_html: { id: "masked_taxa-money", data: {thousands: ".", decimal: ",", suffix:" %"} }, as: :string, autofocus: true %>
        <%= f.input :rate, as: :hidden, input_html: {id: "taxa-money"} %>
        </div>
        <div class="col-sm-6 indexer-mode hidden">
        <%= f.input :indexer, collection: ["CDI", "PRE", "IPC-A+", "IGP-M+"], label: 'Indexador' %>
        </div>
      </div>
    </div>

    <div class="form-actions" id="calculate">
      <%= submit_tag 'Calcular', class: 'btn btn-navy-blue' %>
    </div>
  <% end %>
</div>

<% content_for :js do %>
  <script type="text/javascript">
    $("#masked-money").maskMoney();
    $('#masked_taxa-money').maskMoney();
    $("form.bid_calculation .btn").on('click', function(ev) {
        ev.preventDefault(); // to stop the form from submitting
        /* Validations go here */
        var num = $("#masked-money").maskMoney('unmasked')
        var num1 = $("#masked_taxa-money").maskMoney('unmasked')
/*        $("#real-money").attr("type", "number");*/
/*        $("#taxa-money").attr("type", "number");*/
        $("#real-money").val(num[0]);
        $("#taxa-money").val(num1[0]);
        $(this).closest("form").trigger('submit.rails');
    });
    $("#new_security").submit(function(ev) {
        ev.preventDefault(); // to stop the form from submitting
        /* Validations go here */
        var num = $("#masked-money").maskMoney('unmasked')
        var num1 = $("#masked_taxa-money").maskMoney('unmasked')
/*        $("#real-money").attr("type", "number");*/
/*        $("#taxa-money").attr("type", "number");*/
        $("#real-money").val(num[0]);
        $("#taxa-money").val(num1[0]);
        this.submit(); // If all the validations succeeded
    });
   </script>
<% end %>

app/views/shared/_calculations_card.html.erb
<div class="security-card text-center" id= '<%=@security.issuer.name.downcase.gsub(" ", "-")%>'>
  <%= simple_form_for [:admin, @security, @bid] do |f| %>
  <div class="security-type-logo">
    <%= @security.security_type.name %>
  </div>
  <div class="description">
    <div class="security-card-header">
      <%= image_tag @security.issuer.name.downcase+"-logo.png", height: "40" , id: "logo" %>
      <p><strong>Sua oferta (calcule antes)</strong></p>
    </div>
    <table class="table table-striped" id="calculations">
      <tbody>
        <!-- <tr>
          <td>teste:</td>
          <td><%#= number_to_percentage(rate_calc, precision:2) %></td>
        </tr> -->
        <tr>
          <td>Prazo até Vencimento:</td>
          <td><%= @security.time_to_maturity %> dias</td>
        </tr>
        <tr>
          <td>Rentabilidade Bruta:</td>
          <td>
          <% if !@calculation_price %>
            <%= number_to_percentage(rate_calc, precision:2) %>
          <% else %>
            <%= number_to_percentage(gross_profitability, precision:2) %>
          <% end %>
          </td>
        </tr>
        <tr>
          <td>Rentabilidade Líquida:</td>
          <td>
            <% if !@calculation_price %>
              <%= number_to_percentage(net_rate_calc, precision:2) %>
            <% else %>
              <%= number_to_percentage(net_profitability, precision:2) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Rentabilidade Bruta (%CDI):</td>
          <td>
            <% if !@calculation_price %>
              <%= number_to_percentage((rate_calc.to_f/@security.cdi)*100, precision:2) %>
            <% else %>
              <%= number_to_percentage(gross_profitability_cdi.to_f * 100, precision:2) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Rentabilidade Líquida (%CDI):</td>
          <td>
            <% if !@calculation_price %>
              <%= number_to_percentage((net_rate_calc.to_f/@security.cdi)*100, precision:2) %>
            <% else %>
              <%= number_to_percentage(net_profitability_cdi.to_f * 100, precision:2) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>PU da oferta:</td>
          <td>
              <%= number_to_currency(@bid.price.to_f / @security.quantity, precision:2) %>
          </td>
        </tr>
        <tr>
          <td>Valor da oferta:</td>
          <td>
              <%= number_to_currency(@bid.price, precision:2) %>
          </td>
        </tr>
        <tr>
          <td>Taxa Secondary:</td>
          <td><%= number_to_currency(@bid.comission, precision:2) %></td>
        </tr>
        <tr>
          <td>Valor final (oferta + comissão):</td>
          <td><%= number_to_currency(@bid.comission + @bid.price) %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- <button class="btn btn-navy-blue">Enviar ordem</button> -->
        <%= f.input :price, as: :hidden %>
        <%= f.input :rate, as: :hidden %>
        <%= f.input :indexer, as: :hidden %>
  <%= submit_tag 'Enviar ordem', class: 'btn btn-navy-blue' %>
  <% end %>
</div>

app/views/shared/_fgc.html.erb
<% if @security.security_type.name == "CDB" %>
  <p>Certificado de Depósito Bancário (CDB) - são títulos nominativos emitidos pelos bancos e caixas econômicas vendidos aos investidores como forma de captação de recursos do emissor.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Aplicação garantida pelo Fundo Garantidor de Créditos (FGC) para valores até R$ 250 mil, por CPF ou CNPJ, por instituição ou conglomerado financeiro;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ);</li>
    <li>IOF para resgate antes de 30 dias;</li>
    <li>IR via tabela regressiva.</li>
  </ul>
<% elsif @security.security_type.name == "CRA" %>
  <p>CRA (Certificado de Recebíveis do Agronegócio) - estão vinculados a direitos creditórios originários de negócios realizados, em sua maioria, por produtores rurais ou suas cooperativas, relacionados ao financiamento da atividade agropecuária.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Possibilidade de estruturas com garantias (como alienação da terra e penhor da produção);</li>
    <li>São negociados no balcão e registrados na Cetip ou no BovespaFix;</li>
    <li>Isenção de IR e IOF para pessoa física no rendimento; ganhos de capital auferidos na alienação ou cessão dos ativos são isentos de IR para Pessoa Física (Instrução 1585);</li>
    <li>Destinado exclusivamente a investidores qualificados e profissionais;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ).</li>
  </ul>
  <p><strong>Trata-se de uma modalidade de investimento que não conta com a garantia do Fundo Garantidor de Crédito (FGC).</strong></p>
<% elsif @security.security_type.name == "CRI" %>
  <p>CRI (Certificado de Recebíveis Imobiliários) - são títulos lastreados em créditos imobiliários, representativos de parcelas de um direito creditório.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Possibilidade de estruturas com garantias (como alienação da terra e penhor da produção);</li>
    <li>São negociados no balcão e registrados na Cetip ou no BovespaFix;</li>
    <li>Isenção de IR e IOF para pessoa física no rendimento; ganhos de capital auferidos na alienação ou cessão dos ativos são isentos de IR para Pessoa Física (Instrução 1585);</li>
    <li>Destinado exclusivamente a investidores qualificados e profissionais;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ).</li>
  </ul>
  <p><strong>Trata-se de uma modalidade de investimento que não conta com a garantia do Fundo Garantidor de Crédito (FGC).</strong></p>
<% elsif @security.security_type.name == "DEBENTURE" %>
  <p>Debêntures - as debêntures são valores mobiliários que representam dívidas de médio e longo prazos de Sociedades Anônimas (emissoras).</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>São negociadas no balcão e registradas na Cetip ou no BovespaFix;</li>
    <li>Podem contar com a isenção de IR e IOF (para pessoa física) no rendimento e no ganho de capital, caso estejam enquadradas como debêntures de infraestrutura (Lei 12.431);</li>
    <li>Liquidez restrita no mercado secundário;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ).</li>
  </ul>
  <p><strong>Trata-se de uma modalidade de investimento que não conta com a garantia do Fundo Garantidor de Crédito (FGC).</strong></p>
<% elsif @security.security_type.name == "DPGE" %>
  <p>Depósito a prazo com garantia especial do FGC (DPGE) - depósito a prazo emitido por uma instituição financeira. Os bancos comerciais, múltiplos, de desenvolvimento e investimento, as sociedades de crédito, financiamento e investimento e as caixas econômicos são as instituições autorizadas a emitir este ativo.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Aplicação garantida pelo Fundo Garantidor de Créditos (FGC) para valores até R$20 milhões (principal mais juros), por CPF ou CNPJ, por instituição ou conglomerado financeiro;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ);</li>
    <li>IOF para resgate antes de 30 dias;</li>
    <li>IR via tabela regressiva.</li>
  </ul>
<% elsif @security.security_type.name == "FIDC" %>
  <p>FIDC (Fundo de Investimento em Direitos Creditórios) - Fundo de investimento que destina parcela preponderante de seu patrimônio líquido para aplicação em direitos e títulos representativos de créditos (direitos creditórios) provenientes de operações comerciais, industriais, imobiliárias, financeiras ou de prestação de serviços, entre outras.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>Rentabilidade diferenciada quando comparado a ativos com classificação de risco semelhante;</li>
    <li>Pode ser aberto (permitindo a entrada e saída de cotistas a qualquer tempo) ou fechado (a entrada de cotistas não é permitida após o período de captação, e a saída não é permitida antes do vencimento);</li>
    <li>Pode ter prazo de duração determinado (fundo fechado) ou indeterminado (fundo aberto);</li>
    <li>Destinado exclusivamente a investidores qualificados e profissionais;</li>
    <li>Investimento mínimo inicial de R$ 25 mil;</li>
  </ul>
  <p><strong>Trata-se de uma modalidade de investimento que não conta com a garantia do Fundo Garantidor de Crédito (FGC).</strong></p>
<% elsif @security.security_type.name == "LC" %>
  <p>LC (Letra de Câmbio) - Instrumento de captação das financeiras, com o objetivo de financiar suas atividades. Você empresta dinheiro às financeiras em troca de uma rentabilidade preestabelecida.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Aplicações garantidas pelo Fundo Garantidor de Créditos (FGC) para valores até R$ 250 mil, por CPF ou CNPJ, por instituição ou conglomerado financeiro;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ);</li>
    <li>IOF para resgate antes de 30 dias;</li>
    <li>IR via tabela regressiva.</li>
  </ul>
<% elsif @security.security_type.name == "LCA" %>
  <p>LCA (Letra de Crédito do Agronegócio) - Título emitido por instituições financeiras públicas e privadas, vinculado a direitos creditórios originários do agronegócio.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Aplicações garantidas pelo Fundo Garantidor de Créditos (FGC) para valores até R$ 250 mil, por CPF ou CNPJ, por instituição ou conglomerado financeiro;</li>
    <li>Isenção de IR para pessoa física no rendimento e no ganho de capital;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ);</li>
    <li>IR via tabela regressiva para investidores PJ.</li>
  </ul>
<% elsif @security.security_type.name == "LCI" %>
  <p>LCI (Letra de Crédito Imobiliário) - Instrumento de captação que pode ser emitido por instituições autorizadas pelo Banco Central, com objetivo de financiar o setor imobiliário que tem como lastro financiamentos imobiliários garantidos por hipoteca ou alienação fiduciária do imóvel.
</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Aplicações garantidas pelo Fundo Garantidor de Créditos (FGC) para valores até R$ 250 mil, por CPF ou CNPJ, por instituição ou conglomerado financeiro;</li>
    <li>Isenção de IR para pessoa física no rendimento e no ganho de capital;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ);</li>
    <li>IR via tabela regressiva para investidores PJ.</li>
  </ul>
<% elsif @security.security_type.name == "LF" %>
  <p>LF (Letra Financeira) - Instrumento de captação de recursos exclusivo das instituições financeiras.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>Prazo mínimo de 2 anos (sênior) e 5 anos (subordinada);</li>
    <li>É vedado resgate total ou parcial antes do vencimento;</li>
    <li>Investimento mínimo de R$150 mil (sênior) e R$ 300 mil (subordinada);</li>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ).</li>
  </ul>
  <p><strong>Trata-se de uma modalidade de investimento que não conta com a garantia do Fundo Garantidor de Crédito (FGC).</strong></p>
<% elsif @security.security_type.name == "LFSUB" %>
  <p>LFSUB (Letra Financeira Subordinada) - Instrumento de captação de recursos exclusivo das instituições financeiras.</p>
  <p>CARACTERÍSTICAS:</p>
  <ul>
    <li>Prazo mínimo de 5 anos;</li>
    <li>É vedado resgate total ou parcial antes do vencimento;</li>
    <li>Investimento mínimo de R$ 300 mil;</li>
    <li>A remuneração pode ser em % do CDI, CDI + spread, Índices de preços (ex: IGP-M, IPCA) ou Taxa Prefixada;</li>
    <li>Produto registrado na CETIP em nome do cliente (CPF/CNPJ).</li>
  </ul>
  <p><strong>Trata-se de uma modalidade de investimento que não conta com a garantia do Fundo Garantidor de Crédito (FGC).</strong></p>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path do %>
    <span class="text-logo">secondary.</span>
  <% end %>
  <div class="wrapper">

  <div class="right-content">

  <div class="navbar-middle">

  <% if user_signed_in? %>
    <!-- Links when logged in -->
    <div class="text-right">
      <p class="user-name">
        Bem-vindo <%= current_user.name %>. Seu saldo é <span class="user-account-ballance"><%= number_to_currency(current_user.calc_balance, :unit => "R$ ", :separator => ",", :delimiter => ".") %></span>
        <br>
        <span class="legal-info">Posição até o momento. <%= Time.now.strftime("%d/%m/%Y %H:%M:%S") %></span>
      </p>
    </div>
  <% end %>

  </div>

    <div class="navbar-wagon-right hidden-xs hidden-sm">
  <!-- Right Navigation -->
    <% if user_signed_in? %>
      <!-- Links when logged in -->

      <!-- Messages notifications with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <i class="btn btn-sm btn-navy-blue-navbar dropdown-toggle fa fa-envelope-o" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <%= render "shared/notifications", bids: @notifications %>
          </ul>
        </div>
      </div>

      <!-- Itens in dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <i class="fa fa-user btn btn-sm btn-navy-blue-navbar dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Meus dados") %>
              <% end %>
            </li>
            <li>
              <%= link_to admin_statements_path do %>
                <i class="fa fa-university"></i> <%= t(".profile", default: "Minha conta") %>
              <% end %>
            </li>
            <li>
              <%= link_to admin_securities_path do %>
                <i class="fa fa-file-text-o"></i>  <%= t(".securities", default: "Meus títulos") %>
              <% end %>
            </li>
            <li>
              <%= link_to admin_mybids_path do %>
                <i class="fa fa-handshake-o"></i>  <%= t(".mybids", default: "Minhas ofertas enviadas") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Entrar"), new_user_session_path, class: "btn btn-sm btn-navbar" %>
      <%= link_to t(".sign_up", default: "Crie sua conta"), new_user_registration_path, class: "btn btn-sm btn-navbar-create-account" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Meus dados") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-university"></i> <%= t(".profile", default: "Minha conta") %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_securities_path do %>
            <i class="fa fa-file-text-o"></i>  <%= t(".securities", default: "Meus títulos") %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_mybids_path do %>
            <i class="fa fa-handshake-o"></i>  <%= t(".mybids", default: "Minhas ofertas enviadas") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
      <% else %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".sign_in", default: "Entrar"), new_user_session_path %></li>
        <li><%= link_to t(".sign_up", default: "Crie sua conta"), new_user_registration_path %></li>
      </ul>
      <% end %>
    </div>
  </div>
  </div>
  </div>
  </div>

app/views/shared/_notifications.html.erb
<% if current_user.selling_bids.count.zero? %>
  <li>
    <%= link_to "#" do %>
      <i class="fa fa-envelope"></i> <%= t(".profile", default: "Você não possui novas mensagens") %>
    <% end %>
  </li>
<% else %>
  <% bids.sort_by{|t| - t.created_at.to_i}.first(10).each do |bid| %>
    <% if current_user == bid.buyer %>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-envelope"></i> <%= t(".profile", default: "Você tem uma oferta aceita") %>
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to admin_security_bids_path(bid.security) do %>
          <i class="fa fa-envelope"></i> Você recebeu uma oferta de compra <%= bid.security.issuer.name %> #<%= bid.security.code %>
        <% end %>
      </li>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_numbers.html.erb
<div class="numbers text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>nossos números</h2>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <h3>300+</h3>
          <p>investidores cadastrados</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <h3>10+</h3>
          <p>emissores diferentes</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <h3>R$400 mil</h3>
          <p>negociados semanalmente</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <h3>10</h3>
          <p>tipos de investimentos</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_partner_banks.html.erb
<div class="partner-banks text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>aqui se negocia</h2>
        <br>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= image_tag 'banco do brasil-logo.png', class: "bank-logo" %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= image_tag 'bradesco-logo.png', class: "bank-logo" %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= image_tag 'banco original-logo.png', class: "bank-logo" %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= image_tag 'vale-logo.png', class: "bank-logo" %>
        </div>
      </div>
    </div>
  </div>
<br>
</div>

app/views/shared/_product_info.html.erb
<p>Data de Emissão: <%= @security.issue_date.strftime("%d/%m/%Y") %></p>
<p>Data de Vencimento: <%= @security.maturity.strftime("%d/%m/%Y") %></p>
<p>Em negociação no Secondary até: <%= @security.date_limit.strftime("%d/%m/%Y") %></p>
<p>Taxa: <%= number_to_percentage(@security.rate, precision:2) %> <%= @security.indexer %></p>
<p>Quantidade: <%= @security.quantity %></p>
<p>PU (Preço unitário) atual: <%= number_to_currency(@security.current_value/@security.quantity) %></p>
<p>Valor atual: <%= number_to_currency(@security.current_value) %></p>

app/views/shared/_user_card.html.erb
<div class="user-card text-center ">
  <p><i class="fa fa-user-circle" aria-hidden="true"></i></p>
  <p><strong>Nome:</strong> <%= user.name%></p>
  <p><strong>Usuario Desde:</strong> <%= user.created_at.strftime("%d/%m/%Y")%></p>
  <p><strong>Ofertas atuais:</strong> <%= user.bids.count %></p>
  <p><strong>Títulos cadastrados:</strong> <%= user.securities.count %></p>
  <p><strong>Saldo em conta:</strong> <%= number_to_currency(user.calc_balance, :unit => "R$ ", :separator => ",", :delimiter => ".") %></p>
  <%= link_to "Cadastre um novo título", new_admin_security_path, class: "btn btn-navy-blue btn-sm smaller-btn" %>
</div>

app/views/shared/_what_is.html.erb
<div class="what-is text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>o que é a secondary.</h2>
        <p>A secondary. nasceu para atender a necessidade de liquidez do investidor brasileiro.</p>
        <p>Somos uma plataforma independente onde você pode comprar e vender títulos de renda fixa no mercado secundário.</p>
      </div>
      <div class="col-xs-12">
        <h2>o que é mercado secundário?</h2>
        <p>Toda vez que você compra um título de renda fixa, através de um banco ou corretora, seu dinheiro vai diretamente para a instituição que emitiu o título (banco, empresa), designando assim uma transação no <strong>mercado primário</strong>.</p>
        <p> Uma transação no <strong>mercado secundário</strong> é caracterizada pela troca de valores e titularidade entre os próprios investidores, sem envolver o emissor do título.</p>
      <p></p>
      </div>
    </div>
  </div>
</div>