config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/sysadmin', as: 'rails_admin'
  devise_for :users
  root to: 'securities#index'

  namespace :admin do
    resources :statements, only: [:index]
    resources :securities do
      resources :bids
    end
    get 'mybids', to: 'bids#mybids'
  end

  resources :securities, only: [:index, :show] do
    member do
      post :calculate
    end

    collection do
      get 'search'
      get 'ajax_calculate'
    end
  end

end

app/models/security.rb
class Security < ApplicationRecord
  belongs_to :user
  belongs_to :issuer
  belongs_to :security_type
  has_many :bids, dependent: :destroy
  # validates :mode, presence: true
  validates :code, presence: true
  validates :maturity, presence: true, date: true
  validates :price, presence: true, numericality: true
  validates :date_limit, presence: true, date: true
  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :rate, presence: true, numericality: true
  validates :indexer, presence: true
  validates :unit_price, presence: true, numericality: true
  validates :issue_date, presence: true, date: true
  validate :maturity_cannot_be_in_the_past, on: :create
  validate :date_limit_cannot_be_in_the_past, on: :create
  validate :validate_date_limit_before_maturity, on: :create
  validate :maturity_cannot_be_before_issue_date
  validate :issue_date_cannot_be_in_future
  mount_uploader :file, FileUploader

  def value
    quantity * unit_price
  end

  def time_elapsed
    (Time.current.to_date - issue_date).to_i
  end

  def current_value
    n = time_elapsed * (360.to_f/365)
    pv = value
    i_dia = ((hp12c_interest.to_f / 100)+1)**(1.to_f/360)
    fv = pv.to_f * ((i_dia.to_f)**(n.to_f))
    fv
  end

  def time_to_maturity
    (maturity - Time.current.to_date).to_i
  end


  def cdi
    # site_cetip = Nokogiri::HTML(open("https://www.cetip.com.br/").read)
    # cdi = site_cetip.search('.txt-taxa-porcentagem span#ctl00_Banner_lblTaxDI').text.gsub(/,/,".").gsub(/%/,"").to_f
    9.14
  end

  def cdi_12m
    # site_anbima = Nokogiri::HTML(open("http://www.anbima.com.br/pt_br/informar/estatisticas/precos-e-indices/indicadores.htm").read)
    # cdi_12m = site_anbima.search('.card-body.full.comp-especifico.tab-8col.tab-indicadores .both')
    # ((cdi_12m[1].search("div")[5].text.gsub(/,/,".").gsub(/%/,"").to_f)/100)+1
    11.69
  end

  def ipca
    # site_calculador = Nokogiri::HTML(open("http://www.calculador.com.br/tabela/indice/IPCA").read)
    # ipca = site_calculador.search('#tabela-indice')
    # ipca.search(".text-center")[3].text.gsub(/,/,".").to_f
    2.71
  end

  def igpm
    # site_calculador = Nokogiri::HTML(open("http://www.calculador.com.br/tabela/indice/IGP-M").read)
    # igpm = site_calculador.search('#tabela-indice')
    # igpm.search(".text-center")[3].text.gsub(/,/,".").to_f
    -1.67
  end

  def hp12c_interest
    if indexer == "PRE"
      rate.to_f
    elsif indexer == "CDI"
      rate.to_f * (cdi_12m.to_f/100)
    elsif indexer == "IPC-A+"
      rate.to_f + ipca
    elsif indexer == "IGP-M+"
      rate.to_f + igpm
    end
  end

  private

  def maturity_cannot_be_in_the_past
    if maturity.present? && maturity < Date.today
      errors.add(:maturity, "Título não pode estar vencido")
    end
  end

  def date_limit_cannot_be_in_the_past
    if date_limit.present? && date_limit < Date.today
      errors.add(:date_limit, "Escolha uma data futura")
    end
  end

  def validate_date_limit_before_maturity
    if date_limit.present? && maturity.present? && date_limit > maturity
      errors.add(:date_limit, "Título não pode ser aberto para negociação após data de vencimento")
    end
  end

  def maturity_cannot_be_before_issue_date
    if maturity.present? && issue_date.present? && maturity < issue_date
      errors.add(:maturity, "A data de vencimento tem que ser depois da data de emissão")
    end
  end

  def issue_date_cannot_be_in_future
    if issue_date.present? && issue_date > Date.today
      errors.add(:issue_date, "A data de emissão não pode ser uma data fútura")
    end
  end
end

app/models/security_type.rb
class SecurityType < ApplicationRecord
  has_many :securities
end

app/controllers/admin/securities_controller.rb
class Admin::SecuritiesController < ApplicationController
before_action :set_security, only: [:edit, :update, :destroy, :show]
  def index
    @securities = Security.all.where(user: current_user)

  end

  def new
    @security = Security.new
  end

  def create
    @security = current_user.securities.new(security_params)
    if @security.save
      redirect_to admin_securities_path
    else
      render :new
    end
  end

  def show
  end

  def edit

  end

  def update
    if @security.update(security_params)
      redirect_to admin_securities_path
    else
      render :edit
    end
  end

  def destroy
    @security.destroy
    redirect_to admin_securities_path
  end

  private

  def set_security
    @security = current_user.securities.find(params[:id])
  end

  def security_params
    params.require(:security).permit(:mode, :security_type_id, :issuer_id, :code, :issue_date, :maturity, :price, :date_limit, :status, :quantity, :rate, :indexer, :unit_price)
  end
end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :search]
  before_action :set_security, only: [:show, :calculate]
  layout "landing-page", only: [ :index, :search ]
  def index
    @securities = Security.all
  end

  def show
    @bid = Bid.new
  end

  def search
    @search = Search.new(search_params)
    @securities = Security.all.order("price ASC").where(status: nil)

    if params[:search].present?
      @search.security_type_id = params[:search][:security_type_id]
      @search.price = params[:search][:price]
      @search.maturity = params[:search][:maturity]
      @search.issuer_id = params[:search][:issuer_id]
      @search.rate = params[:search][:rate]
    end

    if @search.security_type_id.present?
      @securities = @securities.where(security_type_id: @search.security_type_id).reorder("price ASC")
    end

    if @search.maturity.present?
      @securities = @securities.where("maturity <= ?", Date.parse(@search.maturity)).reorder("maturity ASC")
    end

    if @search.price.present?
      @securities = @securities.where("price <= ?", @search.price).reorder("price ASC")
    end

    if @search.issuer_id.present?
      @securities = @securities.where(issuer_id: @search.issuer_id).reorder("price ASC")
    end

    if @search.rate.present?
      @securities = @securities.where("rate >=?", @search.rate).reorder("rate DESC")
    end
  end

  def ajax_calculate
    sec = Security.new(params.permit(:issue_date, :maturity, :quantity, :unit_price, :rate, :indexer))
    respond_to do |format|
      format.json { render json: sec.current_value }
    end
  end

  def calculate
    @bid = Bid.new

    if params[:bid_calculation][:mode] == "price"
      @bid.price = params[:bid_calculation][:price]
      n = (@security.time_to_maturity.to_f) * (360.to_f/365)
      pv = @bid.price
      @bid.indexer = @security.indexer
      @bid.rate = ((((hp12c_fv.to_f / pv)**(1.to_f/n))**(360))-1)*100

      @calculation_price = true
    else
      @bid.rate = params[:bid_calculation][:rate]
      @bid.indexer = params[:bid_calculation][:indexer]
      n = (@security.time_to_maturity.to_f) * (360.to_f/365)
      i_dia = ((gross_profitability.to_f / 100)+1)**(1.to_f/360)
      @bid.price = (hp12c_fv.to_f / ((i_dia.to_f)**(n)))
      @calculation_price = false
    end
  end

  private

  def hp12c_fv
    n = (@security.time_to_maturity.to_f + @security.time_elapsed.to_f) * (360.to_f/365)
    pv = @security.value
    i_dia = ((@security.hp12c_interest.to_f / 100)+1)**(1.to_f/360)
    fv = pv.to_f * ((i_dia.to_f)**(n.to_f))
    fv
  end

    def gross_profitability
    indexer = @bid.indexer || @security.indexer
    if indexer == "PRE"
      @bid.rate.to_f
    elsif indexer == "CDI"
      @bid.rate.to_f * (@security.cdi.to_f/100)
    elsif indexer == "IPC-A+"
      @bid.rate.to_f + @security.ipca
    elsif indexer == "IGP-M+"
      @bid.rate.to_f + @security.igpm
    end
  end

    def set_security
        @security = Security.find(params[:id])
    end

    def search_params
      if !params[:search].nil?
      params.require(:search).permit(:price, :maturity, :issuer_id, :rate, :indexer, :security_type_id, :file, :file_cache)
      end
    end
end

app/views/securities/calculate.js.erb
var card = "<%=j render "shared/calculations_card" %>";
$(".security-card").replaceWith(card);

var alert = $("<div>");
alert.addClass("alert alert-info alert-dismissible");
alert.attr('role', 'alert');

var button = $('<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>');
alert.text("Atenção: números podem variar de acordo com o indexador e com o título ofertado");
alert.append(button);

$("#alerts").append(alert);

app/views/securities/current_price.js.erb
var current = <%= security.current_value %>
$('#current-value').replaceWith(current);

app/views/securities/index.html.erb
<%= render 'shared/banner' %>
<div style="background-image: linear-gradient(-20deg, rgb(50,78,123) 0%, rgba(50,78,123,0.95) 75%), url(<%= cl_image_path('blank_rfir8k.jpg') %>);">
  <%= render 'shared/what_is' %>
  <%= render 'shared/value_proposition' %>
  <%= render 'shared/numbers' %>
  <%= render 'shared/what_clients_say' %>
  <%= render 'shared/partner_banks' %>
  <%= render 'shared/footer' %>
</div>

app/views/securities/search.html.erb
<div class="search_banner" style="background-image: linear-gradient(-135deg, rgba(0,63,191,0.6) 0%, rgba(48,52,129,0.95) 85%), url(<%= cl_image_path('banner_x5lv0l.jpg') %>);">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="banner-title">
          <h1>secondary.</h1>
          <p>Encontre os títulos que se encaixam com suas necessidades.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <%= simple_form_for(@search, url: search_securities_path, method: :get) do |f| %>
        <div class="form-input form-group-sm row">
          <div class="input-banner col-xs-12 col-sm-1 col-md-1">
            <%= f.input :security_type_id, prompt: "Tipo", collection: SecurityType.all, include_blank: "Todos", label: false %>
          </div>
          <div class="input-banner  col-xs-12 col-sm-3 col-md-3">
            <%= f.input :price, placeholder: "Quanto quer investir?", as: :integer, label: false %>
          </div>
          <div class="input-banner  col-xs-12 col-sm-3 col-md-3">
            <%= f.input :maturity, placeholder: "Vencimento máximo?", as: :string, input_html: {class: "datepicker"}, label: false %>
          </div>
          <div class="input-banner col-xs-12 col-sm-2 col-md-2">
            <%= f.input :issuer_id, prompt: "Emissor", collection: Issuer.all, include_blank: "Todos", label: false %>
          </div>
          <div class="input-banner col-xs-12 col-sm-1 col-md-1">
            <%= f.input :rate, placeholder: "Taxa", label: false %>
           </div>
          <div class="input-banner col-xs-12 col-sm-2 col-md-2">
            <%= f.input :indexer, prompt: "Indexador", collection: ["CDI", "PRE", "IPC-A+", "IGP-M+"], include_blank: "Todos", label: false %>
          </div>
        </div>
    </div>
    <div class="row">
      <div class="form-input form-group-sm text-center">
        <%= f.button :submit, class: "btn btn-home", value: "Buscar títulos" %>
      </div>
    </div>
      <% end %>
  </div>
</div>

<br>

<div class="container text-center">
  <div class ="row">
    <% if @search.empty? %>
      <h3> Todos os títulos cadastrados </h3>
    <% elsif @securities.empty? %>
      <h3> Nenhum título foi encontrado com esses critérios  </h3>
    <% else %>
      <%= "#{@securities.count} títulos encontrados" %>
    <% end %>
  </div>
  <% @securities.each do |security| %>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
      <%=render 'shared/security_card', security: security, link_path: admin_security_bids_path(security) %>
    </div>
  <% end %>
</div>

<br>
<br>
<br>

<%= render 'shared/footer' %>

app/views/securities/show.html.erb
<div class="container">
  <br>
  <%= link_to 'Voltar', :back, class:"links" %>
  <div class="row">
    <div class="details-card col-md-9" id= '<%=@security.issuer.name.downcase.gsub(" ", "-")%>'>
      <%= image_tag @security.issuer.name.downcase+"-logo.png", height: "100" , id: "logo" %>
      <h1><%= @security.security_type.name %> - <%= @security.issuer.name %></h1>
      <div class="row">
        <div class="col-md-7">
          <%= render 'shared/product_info' %>
          <div id="controls">
          <% if current_user == @security.user %>
            <%= link_to "Editar", edit_admin_security_path, class: "btn btn-primary" %>
            <%= link_to "Deletar", admin_securities_path, method: :delete, data: { confirm: 'Deseja remover este título?' }, class: "btn btn-danger" %>
          <% else %>
          <% end %>
          </div>
        </div>
      <div class="col-md-4">
        <% if current_user != @security.user %>
          <%= render 'shared/bid_card' %>
        <% else %>
        <% end %>
      </div>
    </div>
      <h1> </h1>
      <%= render 'shared/fgc' %>
    </div>
    <div class="col-md-3">
      <% if current_user != @security.user %>
        <%#= render 'shared/calculations_card' %>
        <div class="security-card text-center" id= '<%=@security.issuer.name.downcase.gsub(" ", "-")%>'>
        <div class="security-type-logo">
          <%= @security.security_type.name %>
        </div>
        <div class="description">
          <div class="security-card-header">
            <%= image_tag @security.issuer.name.downcase+"-logo.png", height: "40" , id: "logo" %>
            <p><strong>Sua oferta (calcule antes)</strong></p>
          </div>
          <table class="table table-striped" id="calculations">
            <tbody>
              <tr>
                <td>CDI hoje:</td>
                <td><%= number_to_percentage(@security.cdi, precision:2) %></td>
              </tr>
              <tr>
                <td>CDI ult. 12 meses:</td>
                <td><%= number_to_percentage(@security.cdi_12m, precision:2) %></td>
              </tr>
              <tr>
                <td>IPCA ult. 12 meses:</td>
                <td><%= number_to_percentage(@security.ipca, precision:2) %></td>
              </tr>
              <tr>
                <td>IGMP ult. 12 meses:</td>
                <td><%= number_to_percentage(@security.igpm, precision:2) %></td>
              </tr>
            </tbody>
          </table>
        </div>
      <% else %>
        <%#= render 'shared/user_card' %>
      <% end %>
    </div>
  </div>
</div>